apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: simple-kanban
build:
  artifacts:
  - image: registry.stormpath.net/simple-kanban
    docker:
      dockerfile: Dockerfile
  local:
    push: true
deploy:
  helm:
    releases:
    - name: simple-kanban-dev
      chartPath: helm/simple-kanban
      namespace: apps-dev
      valuesFiles:
      - helm/simple-kanban/values-dev.yaml
portForward:
- resourceType: service
  resourceName: simple-kanban-dev
  port: 8000
  localPort: 8000
profiles:
- name: local
  activation:
    - command: dev
  deploy:
    helm:
      releases:
      - name: simple-kanban-local
        chartPath: helm/simple-kanban
        namespace: default
        valuesFiles:
        - helm/simple-kanban/values-local.yaml
  portForward:
  - resourceType: service
    resourceName: simple-kanban-local
    port: 80
    localPort: 8000
- name: dev
  deploy:
    helm:
      releases:
      - name: simple-kanban-dev
        chartPath: helm/simple-kanban
        namespace: apps-dev
        valuesFiles:
        - helm/simple-kanban/values-dev.yaml
      hooks:
        after:
        - host:
            command: ["./scripts/post-deploy-test.sh", "dev", "full", "soft"]
            os: [darwin, linux]
- name: prod
  deploy:
    helm:
      releases:
      - name: simple-kanban
        chartPath: helm/simple-kanban
        namespace: apps
        valuesFiles:
        - helm/simple-kanban/values-prod.yaml
      hooks:
        after:
        - host:
            command: ["./scripts/post-deploy-test.sh", "prod", "full", "hard"]
            os: [darwin, linux]
- name: feature
  deploy:
    helm:
      releases:
      - name: simple-kanban-dev
        chartPath: helm/simple-kanban
        namespace: apps-dev
        valuesFiles:
        - helm/simple-kanban/values-dev.yaml
