apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: simple-kanban
build:
  artifacts:
  - image: registry.stormpath.net/simple-kanban
    docker:
      dockerfile: Dockerfile
  local:
    push: true
deploy:
  helm:
    releases:
    - name: simple-kanban
      chartPath: helm/simple-kanban
      namespace: apps
      valuesFiles:
      - helm/simple-kanban/values-dev.yaml
portForward:
- resourceType: service
  resourceName: simple-kanban
  port: 8000
  localPort: 8000
profiles:
- name: dev
  deploy:
    helm:
      releases:
      - name: simple-kanban-dev
        chartPath: helm/simple-kanban
        namespace: apps
        valuesFiles:
        - helm/simple-kanban/values-dev.yaml
- name: prod
  deploy:
    helm:
      releases:
      - name: simple-kanban-postgres
        remoteChart: bitnami/postgresql
        version: "16.7.11"
        namespace: apps
        setValues:
          auth.existingSecret: simple-kanban-postgres-secret
          auth.secretKeys.adminPasswordKey: postgres-password
          auth.secretKeys.userPasswordKey: password
          auth.username: kanban
          auth.database: simple_kanban
          primary.persistence.size: 2Gi
          metrics.enabled: true
      - name: simple-kanban-redis
        remoteChart: bitnami/redis
        version: "21.2.3"
        namespace: apps
        setValues:
          auth.existingSecret: simple-kanban-redis-secret
          auth.existingSecretPasswordKey: redis-password
          master.persistence.size: 1Gi
          metrics.enabled: true
      - name: simple-kanban
        chartPath: helm/simple-kanban
        namespace: apps
        valuesFiles:
        - helm/simple-kanban/values-prod.yaml
